const GET_CARS = 'GET_CARS'
const SET_GAME_COUNT = 'SET_GAME_COUNT'
const MOVE_CARS = 'MOVE_CARS'
const RESET_GAME = 'RESET_GAME'
const DISPLAY_WINNERS = 'DISPLAY_WINNERS'

export { GET_CARS, SET_GAME_COUNT, MOVE_CARS, RESET_GAME, DISPLAY_WINNERS }
