export const ERROR_CODES = {
  ERROR_LONG_CAR_NAME: "ERROR_LONG_CAR_NAME",
  ERROR_EMPTY_CAR_NAME: "ERROR_EMPTY_CAR_NAME",
  ERROR_DUPLICATE_CAR_NAME: "ERROR_DUPLICATE_CAR_NAME",
  ERROR_INVALID_CAR_NAME: "ERROR_INVALID_CAR_NAME",
  ERROR_UNKOWN: "ERROR_UNKOWN",
};

export const ERROR_MESSAGES = {
  ERROR_LONG_CAR_NAME: "자동차 이름은 5자 이하로 입력해주세요.",
  ERROR_EMPTY_CAR_NAME: "자동차 이름을 입력해주세요.",
  ERROR_DUPLICATE_CAR_NAME: "중복된 자동차 이름이 있습니다.",
  ERROR_INVALID_CAR_NAME: "유효하지 않은 자동차 이름입니다.",
  ERROR_UNKOWN: "알 수 없는 오류가 발생했습니다.",
};
