const MAX_RANDOM_NUMBER = 9;
const MIN_RANDOM_NUMBER = 0;
const RANDOM_NUMBER_RANGE = 10;

const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 5;

const MIN_USER_COUNT = 2;
const MAX_USER_COUNT = Number.MAX_SAFE_INTEGER;

const MIN_ROUND_COUNT = 1;
const MAX_ROUND_COUNT = 5;

const SPLIT_STANDARD = ',';
const SPLIT_STANDARD_KOR = '쉼표';

const MOVE_STANDARD = 4;

const MOVING_DISTANCE_PER_ROUND = 1;

const SKID_MARK = '-';

const DEFAULT_RACING_ROUND = 5;

module.exports = {
  MAX_RANDOM_NUMBER,
  MIN_RANDOM_NUMBER,
  RANDOM_NUMBER_RANGE,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_USER_COUNT,
  MAX_USER_COUNT,
  MIN_ROUND_COUNT,
  MAX_ROUND_COUNT,
  MOVE_STANDARD,
  SPLIT_STANDARD,
  SPLIT_STANDARD_KOR,
  SKID_MARK,
  DEFAULT_RACING_ROUND,
  MOVING_DISTANCE_PER_ROUND,
};
