const MAX_RANDOM_NUMBER = 9;
const MIN_RANDOM_NUMBER = 0;
const RANDOM_NUMBER_RANGE = 10;

const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 5;

const MIN_USER = 2;
const MAX_USER = Number.MAX_SAFE_INTEGER;

const SPLIT_STANDARD = ',';

const MOVE_STANDARD = 4;

const SKID_MARK = '-';

const DEFAULT_RACING_ROUND = 5;

module.exports = {
  MAX_RANDOM_NUMBER,
  MIN_RANDOM_NUMBER,
  RANDOM_NUMBER_RANGE,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_USER,
  MAX_USER,
  MOVE_STANDARD,
  SPLIT_STANDARD,
  SKID_MARK,
  DEFAULT_RACING_ROUND,
};
