const INPUT_SETTING = {
	SPLITER: ",",
	MAX_LENGTH: 5,
	MIN_CARS: 2,
	REGEX: /^[a-zA-Z]*$/,
};

const CAR_SETTING = {
	CAR_NAME: "pobi",
	CAN_MOVE_NUM: 4,
	DEFAULT_POSITION: 1,
	CAR_RUN_UNIT: 1,
};

const CAR_RACING_GAME_SETTING = {
	DEFAULT_ROUND: 0,
	DEFAULT_WINNER: [],
	ROUND_END: 5,
	RANDOM_MAX: 9,
	RANDOM_MIN: 0,
};

export const SETTING = {
	INPUT_SETTING,
	CAR_SETTING,
	CAR_RACING_GAME_SETTING,
};
