const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 5;

const MIN_TRY_COUNT = 1;

const MIN_RANDOM_NUMBER = 0;
const MAX_RANDOM_NUMBER = 9;
const GO_FLAG_NUMBER = 4;

export {
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_TRY_COUNT,
  MIN_RANDOM_NUMBER,
  MAX_RANDOM_NUMBER,
  GO_FLAG_NUMBER,
};
