const MAX_CAR_NAME_LENTH = 5;
const MIN_CAR_NAME_LENTH = 1;

const MAX_FORWARD_NUMBER = 1;
const MIN_FORWARD_NUMBER = 9;

const MAX_FORWARD_CONDITION = 4;

const CAR_VALIDATION = Object.freeze({
  MAX_CAR_NAME_LENTH,
  MIN_CAR_NAME_LENTH,
  MAX_FORWARD_NUMBER,
  MIN_FORWARD_NUMBER,
  MAX_FORWARD_CONDITION,
});

export default CAR_VALIDATION;
