export const INPUT_CONDITION = {
  SEPARATOR_CAR_NAME: ',',
  MIN_CAR_NAME_LENGTH: 1,
  MAX_CAR_NAME_LENGTH: 5,
  MIN_TRIAL_COUNT: 1,
};

export const GAME_CONDITION = {
  MAX_RANDOM_NUMBER: 9,
  MIN_RANDOM_NUMBER: 0,

  MOVABLE_MIN_NUMBER: 4,
  UNIT_OF_DISTANCE: 1,

  TURN_INTERVAL_TIME: 1000,
  CELEBRATE_TIME: 2000,
};
