const START = 0;
const END = 9;
const PROCESS_INTERVAL_MILLI_SECONDS = 1000;
const CELEBRATION_MESSAGE_INTERVAL_MILLI_SECONDS = 2000;

export {
  START, 
  END, 
  PROCESS_INTERVAL_MILLI_SECONDS,
  CELEBRATION_MESSAGE_INTERVAL_MILLI_SECONDS
};
