export const Constants = {
  CAR_NAME_MIN_LENGTH: 1,
  CAR_NAME_MAX_LENGTH: 5,
  TRY_COUNT_MIN_VALUE: 1,
  TRY_COUNT_MAX_VALUE: 10,
  MOVE_FORWARD_MIN_NUMBER: 4,
  MOVE_FORWARD_MAX_NUMBER: 9,
  RANDOM_NUMBER_MAX_VALUE: 10,
  MILLISECONDS_PER_TRY: 1000,
  INITIAL_TRY_COUNT: 1,
  INCREMENT_PER_TRY: 1,
};
