export const RACING_CAR = {
  NAME_LENGTH_LIMIT: 5,
  MIN_ATTEMPTS_COUNT: 1,

  MOVE_FORWARD_WAITING_TIME: 1000,
  MIN_MOVE_FORWARD_NUMBER: 0,
  MAX_MOVE_FORWARD_NUMBER: 9,
  STANDARD_MOVE_FORWARD_NUMBER: 4,
};
