export const MAX_NAME_LENGTH_LIMIT = 5;
export const RANDOM_NUM_MIN_RANGE = 0;
export const RANDOM_NUM_MAX_RANGE = 10;
export const STANDARD_MOVE_VALUE = 3;

export const notifyTypes = {
  ENTRY_CONFIRM: "ENTRY_CONFIRM",
  COUNT_CONFIRM: "COUNT_CONFIRM",
  PROCESS_RACE: "PROCESS_RESULT",
  GET_RACE_RESULT: "GET_RACE_RESULT",
  RESET_RACE: "RESET_RESULT",
};
